# Change Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Configuration reloaded!"


# Log path
set -g @logging-path "~/.config/tmux/logs"

# Change window and pane index
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Key-bindings for splits
bind - split-window -v -c "#{pane_current_path}"
bind ] split-window -h -c "#{pane_current_path}"

# Key-bindings for resizing pane
bind -r -T prefix k resize-pane -U 5
bind -r -T prefix j resize-pane -D 5
bind -r -T prefix h resize-pane -L 5
bind -r -T prefix l resize-pane -R 5

# Enable mouse
set -g mouse on

# Colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Theme
set -g @catppuccin_flavour 'mocha' # latte,frappe, macchiato or mocha
set -g @catppuccin_status_modules_right "session"
set -g @catppuccin_status_modules_left ""
# set -g @catppuccin_status_connect_separator "yes"
set -g @catppuccin_status_left_separator "█"
# set -g @catppuccin_status_right_separator "█ "
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_middle_separator "█ "

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

