# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Changing default prefix
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

#setting the delay between prefix and command
set -s escape-time 10

# Set bind key to reload configuration file
bind r source-file ~/.config/tmux/tmux.conf \; display ​"Reloaded!"

# splitting panes with | and -
bind ] split-window -h
bind - split-window -v

# Set vi as the default editor
set -g status-keys vi

# Resize panes with vim motions
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Set pane and window numberinf from 1
set -g base-index 1
set -g pane-base-index 1

# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

set -g status-position top

# Theme
set -g @plugin "arcticicestudio/nord-tmux"

run '~/.config/tmux/plugins/tpm/tpm'
