
[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
decorations = "Full"

# dynamic_padding = true
# padding.x = 1
# padding.y = 1

[cursor]
style.shape = "beam"

[scrolling]
history = 100000

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 16.0

[bell]
animation = "Ease"

[general]

live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
