
[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
decorations = "None"

# dynamic_padding = true
padding.x = 6
padding.y = 1

[cursor]
style.shape = "Beam"
style.blinking = "Always"
blink_interval = 200
blink_timeout = 0

[scrolling]
history = 100000

[font]
normal.family = "SauceCodePro Nerd Font Mono"
size = 14.0

[bell]
animation = "Ease"

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Configure Alacritty to open http/https links in the Min browser on Ctrl+Click
[[hints.enabled]]
# This regex matches common HTTP/HTTPS URLs
regex = "(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]"
# The command to execute when a link is clicked.
command = { program = "/Applications/Min.app/Contents/MacOS/Min", args = ["${text}"] }
hyperlinks = true # Enable hyperlinks in the terminal output
post_processing = true # Enable post-processing for hints (usually good to leave true)
mouse.enabled = true # Enable mouse clicking for hints
mouse.mods = "Control" # Require the Control key to be held down for mouse clicks to activate the hint
